services:    # 컨테이너 정의(컨테이너의 집합체를 보주로 서비스라고 함)
  rental-db:
    image: mysql:8.0
    container_name: local_mysql
    platform: linux/x86_64
    environment:   # 환경 변수 설정
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rental_local_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - seat-view:/var/lib/mysql
volumes:
  seat-view :
