spring:
  application:
    name: "Facility-Rental-System"
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
