spring:
  application:
    name: "Facility-Rental-System"
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        show-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8000
