blank_issues_enabled: false
contact_links:
  - name: environment setting
    url: https://github.com/mju-facilty-organization/mju-facilty-BE/blob/main/.github/ISSUE_TEMPLATE/environment.md
    about: Please ask and answer questions here.
